main:
  - identifier: essay
    name: Essay
    pageRef: /essay/
    weight: 10
  - identifier: engineering
    name: Engineering
    pageRef: /engineering/
    weight: 20
  - identifier: ai
    name: AI
    pageRef: /ai/
    weight: 30
  - identifier: business
    name: Business
    pageRef: /business/
    weight: 40
  - identifier: travel
    name: Travel
    pageRef: /travel/
    weight: 50
  - identifier: search
    name: Search
    pageRef: /search/
    weight: 60