main:
  - identifier: essay
    name: Essay
    pageRef: /essay/
    weight: 10
  - identifier: engr
    name: Engineering
    pageRef: /engr/
    weight: 20
  - identifier: mgmt
    name: Management
    pageRef: /mgmt/
    weight: 30
  - identifier: travel
    name: Travel
    pageRef: /travel/
    weight: 40
  - identifier: search
    name: Search
    pageRef: /search/
    weight: 50