baseURL = "https://logischermix.com/"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

# website title
title = "LogischerMix"

# language code ["en", "zh-CN", "fr", "pl", ...]
#languageCode = "en", "zh-CN", "es"
# language name ["English", "简体中文", "Français", "Polski", ...]
#languageName = "English", "简体中文", "Español"

# determines default content language ["en", "zh-cn", "fr", "pl", ...]
defaultContentLanguage = "en"

[languages]
  [languages.en]
    weight = 1
    title = "LogischerMix"
    languageCode = "en"
    languageName = "English"
    [[languages.en.menu.main]]
      weight = 1
      identifier = "Synopsis"
      pre = ""
      post = ""
      name = "Synopsis"
      url = "/synopsis/"
      title = "Synopsis"
    [[languages.en.menu.main]]
      weight = 2
      identifier = "Engineering"
      pre = ""
      post = ""
      name = "Engineering"
      url = "/engr/"
      title = "Engineering"
    [[languages.en.menu.main]]
      weight = 3
      identifier = "Management"
      pre = ""
      post = ""
      name = "Management"
      url = "/mgmt/"
      title = "Management"
    [[languages.en.menu.main]]
      weight = 4
      identifier = "life"
      pre = ""
      post = ""
      name = "Life"
      url = "/life/"
      title = "life"
    [[languages.en.menu.main]]
      weight = 5
      identifier = "travel"
      pre = ""
      post = ""
      name = "Travel"
      url = "/travel/"
      title = "travel"
    [[languages.en.menu.main]]
      weight = 6
      identifier = "categories"
      pre = ""
      post = ""
      name = "Categories"
      url = "/categories/"
      title = ""
    [[languages.en.menu.main]]
      weight = 7
      identifier = "tags"
      pre = ""
      post = ""
      name = "Tags"
      url = "/tags/"
      title = "tags"
    [[languages.en.menu.main]]
      weight = 8
      identifier = "about"
      pre = ""
      post = ""
      name = "About"
      url = "/about/"
      title = "about"

  [languages.zh-cn]
    weight = 2
    title = "LogischerMix"
    languageCode = "zh-CN"
    languageName = "简体中文"
    hasCJKLanguage = true
    [[languages.zh-cn.menu.main]]
      weight = 1
      identifier = "Synopsis"
      pre = ""
      post = ""
      name = "评论"
      url = "/synopsis/"
      title = "Synopsis"
    [[languages.zh-cn.menu.main]]
      weight = 2
      identifier = "Engineering"
      pre = ""
      post = ""
      name = "技术"
      url = "/engr/"
      title = "Engineering"
    [[languages.zh-cn.menu.main]]
      weight = 3
      identifier = "Management"
      pre = ""
      post = ""
      name = "管理"
      url = "/mgmt/"
      title = "Management"
    [[languages.zh-cn.menu.main]]
      weight = 4
      identifier = "life"
      pre = ""
      post = ""
      name = "人生"
      url = "/life/"
      title = "life"
    [[languages.zh-cn.menu.main]]
      weight = 5
      identifier = "travel"
      pre = ""
      post = ""
      name = "旅途"
      url = "/travel/"
      title = "travel"
    [[languages.zh-cn.menu.main]]
      weight = 6
      identifier = "categories"
      pre = ""
      post = ""
      name = "分类"
      url = "/categories/"
      title = ""
    [[languages.zh-cn.menu.main]]
      weight = 7
      identifier = "tags"
      pre = ""
      post = ""
      name = "标签"
      url = "/tags/"
      title = ""
    [[languages.zh-cn.menu.main]]
      weight = 8
      identifier = "about"
      pre = ""
      post = ""
      name = "关于"
      url = "/about/"
      title = "about"

  [languages.es]
    weight = 3
    title = "LogischerMix"
    languageCode = "es"
    languageName = "Español"
    [[languages.es.menu.main]]
      weight = 1
      identifier = "Synopsis"
      pre = ""
      post = ""
      name = "Sinopsis"
      url = "/sinopsis/"
      title = "Sinopsis"
    [[languages.es.menu.main]]
      weight = 2
      identifier = "Engineering"
      pre = ""
      post = ""
      name = "Ingeniería"
      url = "/engr/"
      title = ""
    [[languages.es.menu.main]]
      weight = 3
      identifier = "Management"
      name = "Gestión"
      pre = ""
      post = ""
      url = "/mgmt/"
      title = ""
    [[languages.es.menu.main]]
      weight = 4
      identifier = "life"
      pre = ""
      post = ""
      name = "vida"
      url = "/life/"
      title = ""
    [[languages.es.menu.main]]
      weight = 5
      identifier = "travel"
      pre = ""
      post = ""
      name = "viajar"
      url = "/travel/"
      title = "travel"
    [[languages.es.menu.main]]
      weight = 6
      identifier = "categories"
      pre = ""
      post = ""
      name = "categorias"
      url = "/categories/"
      title = ""
    [[languages.es.menu.main]]
      weight = 7
      identifier = "tags"
      pre = ""
      post = ""
      name = "etiquetas"
      url = "/tags/"
      title = ""
    [[languages.es.menu.main]]
      weight = 8
      identifier = "about"
      pre = ""
      post = ""
      name = "acerca de"
      url = "/about/"
      title = "about"


# Author config
[author]
  name = "LogischerMix | Justin Hu"
  email = "logischermix@gmail.com"
  link = ""

# Menu config
# Multilingual enabled,  menu configuration should be done in languages setting



# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
