baseURL = "https://logischermix.com/"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

# website title
title = "LogischerMix"

# language code ["en", "zh-CN", "fr", "pl", ...]
languageCode = ["en", "zh-CN", "fr"]
# language name ["English", "简体中文", "Français", "Polski", ...]
languageName = ["English", "简体中文", "Français"]

# determines default content language ["en", "zh-cn", "fr", "pl", ...]
defaultContentLanguage = "en"

[languages]
  [languages.en]
    weight = 1
    title = "LogischerMix"
    languageCode = "en"
    languageName = "English"
    [[languages.en.menu.main]]
      weight = 1
      identifier = "Engineering"
      pre = ""
      post = ""
      name = "Engineering"
      url = "/se/"
      title = "Engineering"
    [[languages.en.menu.main]]
      weight = 2
      identifier = "categories"
      pre = ""
      post = ""
      name = "Categories"
      url = "/categories/"
      title = ""
    [[languages.en.menu.main]]
      weight = 3
      identifier = "tags"
      pre = ""
      post = ""
      name = "Tags"
      url = "/tags/"
      title = "tags"
    [[languages.en.menu.main]]
      weight = 4
      identifier = "about"
      pre = ""
      post = ""
      name = "About"
      url = "/about/"
      title = "about"

  [languages.zh-cn]
    weight = 2
    title = "LogischerMix"
    languageCode = "zh-CN"
    languageName = "简体中文"
    hasCJKLanguage = true
    [[languages.zh-cn.menu.main]]
      weight = 1
      identifier = "Engineering"
      pre = ""
      post = ""
      name = "技术"
      url = "/se/"
      title = "Engineering"
    [[languages.zh-cn.menu.main]]
      weight = 2
      identifier = "categories"
      pre = ""
      post = ""
      name = "分类"
      url = "/categories/"
      title = ""
    [[languages.zh-cn.menu.main]]
      weight = 3
      identifier = "tags"
      pre = ""
      post = ""
      name = "标签"
      url = "/tags/"
      title = ""
    [[languages.zh-cn.menu.main]]
      weight = 4
      identifier = "about"
      pre = ""
      post = ""
      name = "关于"
      url = "/about/"
      title = "about"

  [languages.fr]
    weight = 3
    title = "LogischerMix"
    languageCode = "fr"
    languageName = "Français"
    [[languages.fr.menu.main]]
      weight = 1
      identifier = "Engineering"
      pre = ""
      post = ""
      name = "Ingénierie"
      url = "/se/"
      title = "Ingénierie"
    [[languages.fr.menu.main]]
      weight = 2
      identifier = "categories"
      name = "Catégories"
      pre = ""
      post = ""
      url = "/categories/"
      title = ""
    [[languages.fr.menu.main]]
      weight = 3
      identifier = "tags"
      pre = ""
      post = ""
      name = "Balises"
      url = "/tags/"
      title = ""
    [[languages.fr.menu.main]]
      weight = 4
      identifier = "about"
      pre = ""
      post = ""
      name = "à propos de"
      url = "/about/"
      title = "about"


# Author config
[author]
  name = "LogischerMix | Justin Hu"
  email = ""
  link = ""

# Menu config
# Multilingual enabled,  menu configuration should be done in languages setting



# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
